import { Question } from './types';

export const defaultQuestions: Question[] = [
  // Stations 1-12: Rừng rậm (Multiple Choice)
  {
    station: 1,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Một cửa hàng có $35$ thùng nước ngọt. Sau khi bán đi $12$ thùng, cửa hàng còn lại bao nhiêu thùng nước ngọt?',
    options: ['$23$ thùng', '$25$ thùng', '$27$ thùng', '$22$ thùng'],
    correctAnswer: '$23$ thùng',
    explanation: 'Ta thực hiện phép tính trừ: $35 - 12 = 23$ thùng.',
  },
  {
    station: 2,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Hình vuông có độ dài cạnh là $8\\text{ cm}$ thì có chu vi là bao nhiêu?',
    options: ['$16\\text{ cm}$', '$32\\text{ cm}$', '$64\\text{ cm}$', '$24\\text{ cm}$'],
    correctAnswer: '$32\\text{ cm}$',
    explanation: 'Chu vi hình vuông được tính bằng công thức: $\\text{Cạnh} \\times 4 = 8 \\times 4 = 32\\text{ cm}$.',
  },
  {
    station: 3,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Tìm $x$, biết: $x \\times 6 = 54$.',
    options: ['$x = 8$', '$x = 7$', '$x = 9$', '$x = 6$'],
    correctAnswer: '$x = 9$',
    explanation: 'Ta tìm $x$ bằng cách lấy tích chia cho thừa số đã biết: $x = 54 \\div 6 = 9$.',
  },
  {
    station: 4,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Phân số nào dưới đây bằng phân số $\\frac{3}{4}$?',
    options: ['$\\frac{9}{12}$', '$\\frac{6}{10}$', '$\\frac{5}{8}$', '$\\frac{12}{15}$'],
    correctAnswer: '$\\frac{9}{12}$',
    explanation: 'Nhân cả tử và mẫu của $\\frac{3}{4}$ với $3$ ta được: $\\frac{3 \\times 3}{4 \\times 3} = \\frac{9}{12}$.',
  },
  {
    station: 5,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Một thửa ruộng hình chữ nhật có chiều dài $20\\text{ m}$, chiều rộng $15\\text{ m}$. Hãy tính diện tích thửa ruộng đó.',
    options: ['$35\\text{ m}^2$', '$70\\text{ m}^2$', '$300\\text{ m}^2$', '$150\\text{ m}^2$'],
    correctAnswer: '$300\\text{ m}^2$',
    explanation: 'Diện tích hình chữ nhật là: $\\text{Chiều dài} \\times \\text{Chiều rộng} = 20 \\times 15 = 300\\text{ m}^2$.',
  },
  {
    station: 6,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Một lớp học có $32$ học sinh. Số học sinh nữ chiếm $\\frac{1}{4}$ số học sinh cả lớp. Hỏi lớp có bao nhiêu học sinh nam?',
    options: ['$8$ học sinh', '$24$ học sinh', '$16$ học sinh', '$20$ học sinh'],
    correctAnswer: '$24$ học sinh',
    explanation: 'Số học sinh nữ là: $32 \\div 4 = 8$ học sinh. Số học sinh nam là: $32 - 8 = 24$ học sinh.',
  },
  {
    station: 7,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Cách tính nhanh nào đúng cho biểu thức tích sau: $125 \\times 8$?',
    options: ['$100$', '$1000$', '$10000$', '$800$'],
    correctAnswer: '$1000$',
    explanation: 'Đây là phép nhân cơ bản cần nhớ: $125 \\times 8 = 1000$.',
  },
  {
    station: 8,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Tìm số trung bình cộng của ba số sau: $14$, $18$ và $28$.',
    options: ['$20$', '$18$', '$22$', '$24$'],
    correctAnswer: '$20$',
    explanation: 'Trung bình cộng = $\\frac{14 + 18 + 28}{3} = \\frac{60}{3} = 20$.',
  },
  {
    station: 9,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Đổi số đo khối lượng sau sang kg: $2$ tạ $5\\text{ kg}$.',
    options: ['$25\\text{ kg}$', '$205\\text{ kg}$', '$250\\text{ kg}$', '$2005\\text{ kg}$'],
    correctAnswer: '$205\\text{ kg}$',
    explanation: '$1$ tạ = $100\\text{ kg}$. Do đó, $2$ tạ $5\\text{ kg} = 200\\text{ kg} + 5\\text{ kg} = 205\\text{ kg}$.',
  },
  {
    station: 10,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Một xe máy di chuyển $80\\text{ km}$ trong vòng $2$ giờ. Vận tốc trung bình của xe máy là bao nhiêu?',
    options: ['$40\\text{ km/h}$', '$30\\text{ km/h}$', '$50\\text{ km/h}$', '$45\\text{ km/h}$'],
    correctAnswer: '$40\\text{ km/h}$',
    explanation: 'Vận tốc = $\\frac{\\text{Quãng đường}}{\\text{Thời gian}} = \\frac{80}{2} = 40\\text{ km/h}$.',
  },
  {
    station: 11,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Một mẫu biểu diễn trên bản đồ tỉ lệ $1 : 10000$ là $5\\text{ cm}$. Độ dài thực tế tương ứng là bao nhiêu mét?',
    options: ['$50\\text{ m}$', '$500\\text{ m}$', '$5000\\text{ m}$', '$50000\\text{ m}$'],
    correctAnswer: '$500\\text{ m}$',
    explanation: 'Khoảng cách thực tế = $5 \\times 10000 = 50000\\text{ cm} = 500\\text{ m}$.',
  },
  {
    station: 12,
    landscape: 'Rừng rậm',
    type: 'multiple-choice',
    questionText: 'Tìm số vừa chia hết cho $2$, chia hết cho $5$, lại chia hết cho $3$ trong các số sau đây.',
    options: ['$125$', '$230$', '$150$', '$312$'],
    correctAnswer: '$150$',
    explanation: 'Số chia hết cho $2$ và $5$ phải có tận cùng là $0$ (đáp án $230$ hoặc $150$). Tổng các chữ số của $150$ là $1+5+0 = 6$ (chia hết cho $3$), nên $150$ chia hết cho cả ba số.',
  },

  // Stations 13-16: Hang động (True/False)
  {
    station: 13,
    landscape: 'Hang động',
    type: 'true-false',
    questionText: 'Xác định tính Đúng / Sai của các mệnh đề sau về công thức hình học lý thuyết:',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Sai,Đúng,Đúng,Sai',
    explanation: 'a) Sai: Diện tích hình tròn là $S = r \\times r \\times 3.14$.\nb) Đúng: Đường kính $d = 2r$.\nc) Đúng: Tam giác đều có $3$ trục đối xứng đi qua đỉnh và trung điểm cạnh đối diện.\nd) Sai: Ba góc của tam giác đều bằng $60^\\circ$ (Tổng ba góc là $180^\\circ$).',
    subStatements: [
      { label: 'a)', text: 'Diện tích hình tròn bán kính $r$ được tính bằng $S = r \\times 2 \\times 3.14$.', correctAnswer: 'Sai' },
      { label: 'b)', text: 'Đường kính hình tròn gấp $2$ lần bán kính.', correctAnswer: 'Đúng' },
      { label: 'c)', text: 'Một hình tam giác đều luôn luôn có đúng $3$ trục đối xứng.', correctAnswer: 'Đúng' },
      { label: 'd)', text: 'Hình tam giác đều luôn luôn có một góc vuông hoặc góc tù.', correctAnswer: 'Sai' }
    ]
  },
  {
    station: 14,
    landscape: 'Hang động',
    type: 'true-false',
    questionText: 'Xét tính Đúng / Sai của các lời phát biểu liên quan đến số nguyên tố sau:',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Sai,Đúng,Đúng,Sai',
    explanation: 'a) Sai: Số $2$ là số nguyên tố chẵn duy nhất.\nb) Đúng: Mọi số nguyên tố đều lớn hơn $1$.\nc) Đúng: Các thừa số nguyên tố của $10$ là $2$ và $5$.\nd) Sai: Số $1$ không phải là số nguyên tố mà cũng không phải hợp số.',
    subStatements: [
      { label: 'a)', text: 'Mọi số nguyên tố đều là số lẻ.', correctAnswer: 'Sai' },
      { label: 'b)', text: 'Số nguyên tố là số tự nhiên lớn hơn $1$, chỉ có hai ước là $1$ và chính nó.', correctAnswer: 'Đúng' },
      { label: 'c)', text: 'Số $10$ có đúng hai ước số nguyên tố khác nhau.', correctAnswer: 'Đúng' },
      { label: 'd)', text: 'Số $1$ là số nguyên tố nhỏ nhất.', correctAnswer: 'Sai' }
    ]
  },
  {
    station: 15,
    landscape: 'Hang động',
    type: 'true-false',
    questionText: 'Xem xét các nhận định về quy luật phân số và tỉ số phần trăm sau đây:',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng,Đúng,Sai,Sai',
    explanation: 'a) Đúng: $\\frac{15}{25}$ rút gọn cho $5$ được $\\frac{3}{5}$.\nb) Đúng: $0.75 = \\frac{75}{100} = 75\\%$.\nc) Sai: $\\frac{1}{2} + \\frac{1}{3} = \\frac{5}{6}$ (không phải $\\frac{2}{5}$).\nd) Sai: $\\frac{7}{4} > \\frac{5}{4}$.',
    subStatements: [
      { label: 'a)', text: 'Phân số $\\frac{15}{25}$ tối giản rút gọn hoàn toàn sẽ bằng $\\frac{3}{5}$.', correctAnswer: 'Đúng' },
      { label: 'b)', text: 'Số định dạng thập phân $0.75$ tương đương với tỉ số $75\\%$.', correctAnswer: 'Đúng' },
      { label: 'c)', text: 'Cộng phân số: $\\frac{1}{2} + \\frac{1}{3} = \\frac{2}{5}$.', correctAnswer: 'Sai' },
      { label: 'd)', text: 'Phân số $\\frac{7}{4}$ nhỏ hơn phân số $\\frac{5}{4}$.', correctAnswer: 'Sai' }
    ]
  },
  {
    station: 16,
    landscape: 'Hang động',
    type: 'true-false',
    questionText: 'Xác định các khẳng định về tính chất phép tính và chia hết sau đúng hay sai:',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng,Đúng,Sai,Đúng',
    explanation: 'a) Đúng: Số chia hết cho $5$ có chữ số tận cùng là $0$ hoặc $5$.\nb) Đúng: Tổng các chữ số chia hết cho $9$ thì chắc chắn chia hết cho $3$.\nc) Sai: Ví dụ số $12$ chia hết cho $3$ nhưng không chia hết cho $9$.\nd) Đúng: Tính chất phân phối $a \\times (b + c) = a \\times b + a \\times c$.',
    subStatements: [
      { label: 'a)', text: 'Số tự nhiên có chữ số tận cùng là $0$ hoặc $5$ thì chia hết cho $5$.', correctAnswer: 'Đúng' },
      { label: 'b)', text: 'Số chia hết cho $9$ thì chắc chắn chia hết cho $3$.', correctAnswer: 'Đúng' },
      { label: 'c)', text: 'Số chia hết cho $3$ thì chắc chắn chia hết cho $9$.', correctAnswer: 'Sai' },
      { label: 'd)', text: 'Biểu thức nhân phân phối: $a \\times (b + c) = a \\times b + a \\times c$.', correctAnswer: 'Đúng' }
    ]
  },

  // Stations 17-22: Thung lũng sương mù (Short Answer)
  {
    station: 17,
    landscape: 'Thung lũng sương mù',
    type: 'short-answer',
    questionText: 'Tìm số tự nhiên $x$, biết: $3x - 5 = 10$. (Ghi rõ giá trị bằng chữ số)',
    correctAnswer: '5',
    explanation: '$3x - 5 = 10$ \n=> $3x = 10 + 5 = 15$ \n=> $x = 15 \\div 3 = 5$.',
    keywords: ['5', 'x=5', 'x = 5', 'năm'],
  },
  {
    station: 18,
    landscape: 'Thung lũng sương mù',
    type: 'short-answer',
    questionText: 'Hãy tính tổng các số tự nhiên lẻ từ $1$ đến $39$ (Tổng của $20$ số lẻ đầu tiên).',
    correctAnswer: '400',
    explanation: 'Tổng của $n$ số lẻ đầu tiên bằng $n^2$: $20 \\times 20 = 400$.',
    keywords: ['400', 'bốn trăm'],
  },
  {
    station: 19,
    landscape: 'Thung lũng sương mù',
    type: 'short-answer',
    questionText: 'Một hình lập phương có diện tích toàn phần là $150\\text{ cm}^2$. Hỏi độ dài một cạnh của hình lập phương đó bằng bao nhiêu cm? (Chỉ điền con số)',
    correctAnswer: '5',
    explanation: 'Diện tích toàn phần của hình lập phương bằng $6$ lần diện tích một mặt. Do đó diện tích một mặt là: $150 \\div 6 = 25\\text{ cm}^2$. Suy ra độ dài cạnh bằng $5\\text{ cm}$ (vì $5 \\times 5 = 25$).',
    keywords: ['5', '5cm', '5 cm'],
  },
  {
    station: 20,
    landscape: 'Thung lũng sương mù',
    type: 'short-answer',
    questionText: 'Tính giá trị của biểu thức sau: $A = (2026 - 2025) \\times 50 + 150$.',
    correctAnswer: '200',
    explanation: 'Nhân chia trước cộng trừ sau: $(1) \\times 50 + 150 = 50 + 150 = 200$.',
    keywords: ['200', 'hai trăm'],
  },
  {
    station: 21,
    landscape: 'Thung lũng sương mù',
    type: 'short-answer',
    questionText: 'Số tiếp theo trong quy luật dãy số sau là số mấy: $1, 4, 9, 16, 25, \\dots$',
    correctAnswer: '36',
    explanation: 'Dãy số gồm các bình phương tăng dần: $1^2, 2^2, 3^2, 4^2, 5^2$. Số tiếp theo là $6^2 = 36$.',
    keywords: ['36', 'ba mươi sáu'],
  },
  {
    station: 22,
    landscape: 'Thung lũng sương mù',
    type: 'short-answer',
    questionText: 'Một hình tròn có bao nhiêu trục đối xứng?',
    correctAnswer: 'Vô số',
    explanation: 'Bất kỳ đường thẳng nào đi qua tâm hình tròn đều là một trục đối xứng của hình tròn đó, do đó có vô số trục đối xứng.',
    keywords: ['vô số', 'vô hạn', 'nhiều', 'vô vàn'],
  }
];
